FLASK_SECRET_KEY = '\x0c\xb5UK\xa8\xc4\xc7\xf1\x03\xe9+\xa3\xac:~Ys\x8aW`+ -\x00'

# Dropbox API variables
DROPBOX_APP_KEY = "nyc0pnugsh7ix0v"
DROPBOX_APP_SECRET = "u2i1rvdkmztmv7g"
OAUTH_REDIRECT_URI = None #!#

# Xero API variables
XERO_CLIENT_KEY = 'ADATDGXMOMVM1ASRTQTXDOHRUQNNO7'
XERO_CLIENT_SECRET = 'F4EEJL5ZLPHAC5JJJ5IVI1IHXJHADO'